fix

diff --git a/.github/workflows/rw-git-merge-test.yml b/.github/workflows/rw-git-merge-test.yml
--- a/.github/workflows/rw-git-merge-test.yml
+++ b/.github/workflows/rw-git-merge-test.yml
@@ -3,10 +3,16 @@ name: Automated Merge and Conflict Resolution
 on:
   workflow_call:
     inputs:
-      branch_name:
+      source-branch:
         required: false
         type: string
         default: 'release'
+      target-branch:
+        required: false
+        type: string
+        default: 'master'
+
+        
     outputs:
       pull-request-url:
         description: "The URL of the created Pull Request"
@@ -19,11 +25,12 @@ jobs:
   merge-and-resolve-conflicts:
     runs-on: ubuntu-latest
     outputs:
-      pr_url: ${{ steps.create_pr.outputs.pr_url }}
-      pr_has_conflicts: ${{ steps.create_pr.outputs.pr_has_conflicts }}
+      pr_url: ${{ steps.prepare-pr.outputs.pr_url }}
+      pr_has_conflicts: ${{ steps.prepare-pr.outputs.pr_has_conflicts }}
     steps:
+
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
@@ -33,92 +40,60 @@ jobs:
           git config user.email 'github-actions@github.com'
 
       - name: Merge and Resolve Conflicts or Create Pull Request
-        id: create_pr
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        id: prepare-pr
         run: |
+
           # Checkout the target branch
-          git checkout ${{ inputs.branch_name }}
+          git checkout $SOURCE_BRANCH
           
           # Define temporary branch name
-          TEMP_BRANCH="${{ inputs.branch_name }}2master"
-          
+          TMP_BRANCH=$SOURCE_BRANCH-to-$TARGET_BRANCH
+           
           # Check if the remote temporary branch exists and delete it if it does
-          if git ls-remote --heads origin "$TEMP_BRANCH" | grep "$TEMP_BRANCH" >/dev/null; then
-              echo "Remote branch $TEMP_BRANCH exists. Deleting..."
-              git push origin --delete "$TEMP_BRANCH"
+          if git ls-remote --heads origin "$TMP_BRANCH" | grep "$TMP_BRANCH" >/dev/null; then
+               echo "Remote branch $TMP_BRANCH exists. Deleting..."
+               git push origin --delete "$TMP_BRANCH"
           fi
-          
+           
           # Check if local temporary branch exists and delete it if it does
-          if git rev-parse --verify "$TEMP_BRANCH" >/dev/null 2>&1; then
-              echo "Local branch $TEMP_BRANCH exists. Deleting..."
-              git branch -D "$TEMP_BRANCH"
+          if git rev-parse --verify "$TMP_BRANCH" >/dev/null 2>&1; then
+              echo "Local branch $TMP_BRANCH exists. Deleting..."
+              git branch -D "$TMP_BRANCH"
           fi
-          
-          # Create a temporary branch
-          git checkout -b "$TEMP_BRANCH"
-          
-          # Attempt to merge master into the temporary branch
-          echo "Attempting to merge master into $TEMP_BRANCH..."
-          git merge origin/master --no-commit --no-ff || true  # Proceed even if merge fails
-          MERGE_STATUS=$(git ls-files -u | wc -l)  # Count unmerged files
-          
-          echo "Number of files with merge conflicts: $MERGE_STATUS"
-          
-          if [ $MERGE_STATUS -ne 0 ]; then
-            echo "Conflicts detected during merge. Attempting to resolve..."
-            
-            # Collect conflicting package.json and version-policies.json files
-            CONFLICTING_FILES=$(git diff --name-only --diff-filter=U | grep -E 'package.json|version-policies.json')
-            echo "Conflicting Files:"
-            echo "$CONFLICTING_FILES"
-            
-            if [ ! -z "$CONFLICTING_FILES" ]; then
-              # Resolve conflicts by accepting changes from master for these files
-              for FILE in $CONFLICTING_FILES; do
-                echo "Resolving conflict in $FILE"
-                git checkout --theirs "$FILE"
-                git add "$FILE"
-              done
-              
-              REMAINING_CONFLICTS=$(git ls-files -u | wc -l)
-              if [ "$REMAINING_CONFLICTS" -eq 0 ]; then
-                # If no more conflicts, commit the merge
-                git commit -m "Merge master into $TEMP_BRANCH with resolved conflicts"
-                echo "Conflicts resolved and merge committed successfully."
-              else
-                echo "Remaining conflicts after resolution attempt:"
-                git diff --name-only --diff-filter=U
-              fi
-            fi
-            
-            # Whether resolved or not, push the temporary branch and create a PR
-            git push origin "$TEMP_BRANCH" --force
-            PR_TITLE="Auto-resolved $TEMP_BRANCH into master"
-            PR_BODY="This PR is created automatically by GitHub Actions."
-            if [ "$REMAINING_CONFLICTS" -ne 0 ]; then
-              PR_TITLE="Resolve Merge Conflicts: $TEMP_BRANCH"
-              PR_BODY="This PR is created automatically by GitHub Actions due to unresolved conflicts after merging 'master' into '$TEMP_BRANCH'. Manual conflict resolution is required."
-            fi
-            PR_OUTPUT=$(gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base master --head "$TEMP_BRANCH")
-            echo "$PR_OUTPUT"
-            PR_URL=$(echo "$PR_OUTPUT" | grep -o 'https://github.com[^ ]*')
-            echo "Pull Request URL: $PR_URL"
-            echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
-            echo "pr_has_conflicts=true" >> $GITHUB_OUTPUT
-            
+           
+          # Create a temporary branch         
+
+          git checkout -b $TMP_BRANCH
+          # rush bump to something that's in master
+          git merge --verbose origin/$TARGET_BRANCH || true
+
+          # we are resolving only conflicts which we can do, we silently ignore other potential conflits
+          conflicting_files=$(git diff --name-only --diff-filter=U | grep -E 'package.json|version-policies.json')
+
+          # perform back-merge resolution
+          for file in $conflicting_files
+          do
+              git checkout --theirs $file
+              git add $file
+          done
+
+          has_conflicts=false
+          conflicting_files=$(git diff --name-only --diff-filter=U)
+          if [ -n "$conflicting_files" ]; then
+            echo "There are conflicts which still need to be resolved, aborting"
+            has_conflicts=true
+            git merge --abort
           else
-            echo "No conflicts detected. Committing the merge..."
-            git commit -m "Merge master into $TEMP_BRANCH"
-            echo "Merge committed successfully."
-            
-            # Push the temporary branch and create a PR
-            git push origin "$TEMP_BRANCH" --force
-            PR_OUTPUT=$(gh pr create --title "Auto-resolved $TEMP_BRANCH into master" --body "This PR is created automatically by GitHub Actions after successfully merging 'master' into '$TEMP_BRANCH' without conflicts." --base master --head "$TEMP_BRANCH")
-            echo "$PR_OUTPUT"
-            PR_URL=$(echo "$PR_OUTPUT" | grep -o 'https://github.com[^ ]*')
-            echo "Pull Request URL: $PR_URL"
-            echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
-            echo "pr_has_conflicts=false" >> $GITHUB_OUTPUT
+            git commit --no-verify -m "Resolved merge conflicts to match $TARGET_BRANCH"
+            git push origin $TMP_BRANCH
           fi
 
+          PR_OUTPUT=$(gh pr create --title "Merge $SOURCE_BRANCH into $TARGET_BRANCH" --body "This PR is created automatically by GitHub Actions. from $SOURCE_BRANCH into $TARGET_BRANCH via temporary branch $TMP_BRANCH" --base $TARGET_BRANCH --head "$TMP_BRANCH")
+          PR_URL=$(echo "$PR_OUTPUT" | grep -o 'https://github.com[^ ]*')
+          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
+          echo "pr_has_conflicts=$has_conflicts" >> $GITHUB_OUTPUT
+        env:
+          SOURCE_BRANCH: ${{ inputs.source-branch }}
+          TARGET_BRANCH: ${{ inputs.target-branch }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        shell: bash
